import { GoogleGenerativeAI } from '@google/generative-ai';
import { writeFileSync } from 'fs';
import { join } from 'path';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

const BACKGROUND_PROMPT = `Detailed pixel art game background, isometric view, underwater restaurant interior called the Chum Bucket. Left side has empty serving counter, old fryer, stack of buckets, dusty cash register, empty stools. Right side has computer monitor on desk (named Karen), whiteboard with evil plans, small cot bed, glowing tip jar. Gray metal walls, tiled floor, pipes on ceiling, dim warm lamp lighting, blue-green underwater tint, abandoned but cozy atmosphere, 16-bit style, no characters, wide view, game asset.

Style requirements:
- Pixel art, 16-bit retro game aesthetic
- 512x256 resolution (wide landscape)
- Clean pixel edges, no anti-aliasing
- Atmospheric lighting with warm lamp glow
- Blue-green underwater color palette
- Detailed interior with all mentioned elements
- No characters or people
- Horizontal game background format`;

async function generateBackground() {
  console.log('[BACKGROUND] Starting generation...');
  console.log('[BACKGROUND] Using API key:', process.env.GEMINI_API_KEY ? 'Set' : 'NOT SET');

  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY environment variable not set');
  }

  try {
    // Try gemini-1.5-pro-latest which should support image generation
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-pro-latest' });

    const result = await model.generateContent([BACKGROUND_PROMPT]);
    const response = result.response;

    // Gemini 2.0 Flash returns image in parts
    const imagePart = response.candidates?.[0]?.content?.parts?.find(
      (part: any) => part.inlineData?.mimeType?.startsWith('image/')
    );

    if (!imagePart || !imagePart.inlineData) {
      throw new Error('No image generated by Gemini');
    }

    // Convert base64 to buffer
    const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');

    console.log('[BACKGROUND] Image generated, size:', imageBuffer.length, 'bytes');

    // Save to frontend public folder
    const frontendPath = join(__dirname, '../../../frontend/public/backgrounds');
    const outputPath = join(frontendPath, 'chum-bucket-interior.png');

    // Create directory if it doesn't exist
    const { mkdirSync } = await import('fs');
    try {
      mkdirSync(frontendPath, { recursive: true });
    } catch (err) {
      // Directory already exists
    }

    writeFileSync(outputPath, imageBuffer);
    console.log('[BACKGROUND] Saved to:', outputPath);
    console.log('[BACKGROUND] ✅ Background generated successfully!');

  } catch (error) {
    console.error('[BACKGROUND] Generation failed:', error);
    throw error;
  }
}

// Run the script
generateBackground().catch((err) => {
  console.error('Failed to generate background:', err);
  process.exit(1);
});
