import { GoogleGenerativeAI } from '@google/generative-ai';
import type { VillainTraits, BodyColor, Hat, EyeColor, Accessory, Expression, Background } from '../types';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// Trait arrays for randomization
const BODY_COLORS: BodyColor[] = ['green', 'blue', 'purple', 'red', 'gold', 'teal'];
const HATS: Hat[] = ['none', 'chef hat', 'crown', 'pirate hat', 'top hat', 'helmet'];
const EYE_COLORS: EyeColor[] = ['red', 'yellow', 'blue', 'pink', 'gold'];
const ACCESSORIES: Accessory[] = ['none', 'monocle', 'eyepatch', 'scar', 'sunglasses'];
const EXPRESSIONS: Expression[] = ['evil grin', 'worried', 'scheming', 'angry', 'happy'];
const BACKGROUNDS: Background[] = ['chum bucket', 'underwater', 'purple', 'orange', 'teal'];

function randomFromArray<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateRandomTraits(): VillainTraits {
  return {
    bodyColor: randomFromArray(BODY_COLORS),
    hat: randomFromArray(HATS),
    eyeColor: randomFromArray(EYE_COLORS),
    accessory: randomFromArray(ACCESSORIES),
    expression: randomFromArray(EXPRESSIONS),
    background: randomFromArray(BACKGROUNDS),
  };
}

function buildPrompt(traits: VillainTraits): string {
  const { bodyColor, hat, eyeColor, accessory, expression, background } = traits;

  let prompt = `Create a pixel art profile picture of Sheldon J. Plankton from SpongeBob SquarePants.

Character description:
- Small copepod creature with ${bodyColor} body
- ONE large eye with ${eyeColor} iris (very important - single cyclopean eye)
- Two antennae on top of head
- Small arms and legs
- ${expression} expression`;

  if (hat !== 'none') {
    prompt += `\n- Wearing a ${hat} on head`;
  }

  if (accessory !== 'none') {
    prompt += `\n- Has ${accessory} accessory`;
  }

  prompt += `\n\nBackground: ${background} themed background`;

  prompt += `\n\nStyle requirements:
- Pixel art style, 512x512 resolution
- Clean, vibrant colors
- Sharp pixel edges, no anti-aliasing blur
- Centered composition
- Profile picture format (character takes up most of frame)
- Retro game aesthetic
- Make it look like a collectible NFT PFP

CRITICAL: Plankton has ONE EYE ONLY - a single large cyclops eye in the center. Do NOT give him two eyes.`;

  return prompt;
}

export async function generateVillainImage(traits?: VillainTraits): Promise<{
  imageBuffer: Buffer;
  traits: VillainTraits;
}> {
  const villainTraits = traits || generateRandomTraits();
  const prompt = buildPrompt(villainTraits);

  console.log('[GEMINI] Generating villain with traits:', villainTraits);

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-exp' });

    const result = await model.generateContent([prompt]);
    const response = result.response;

    // Gemini 2.0 Flash returns image in parts
    const imagePart = response.candidates?.[0]?.content?.parts?.find(
      (part: any) => part.inlineData?.mimeType?.startsWith('image/')
    );

    if (!imagePart || !imagePart.inlineData) {
      throw new Error('No image generated by Gemini');
    }

    // Convert base64 to buffer
    const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');

    console.log('[GEMINI] Image generated successfully, size:', imageBuffer.length, 'bytes');

    return {
      imageBuffer,
      traits: villainTraits,
    };
  } catch (error) {
    console.error('[GEMINI] Image generation failed:', error);
    throw new Error(`Failed to generate villain image: ${error}`);
  }
}
