#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KEYS_DIR="$SCRIPT_DIR/keys"
ENV_FILE="$SCRIPT_DIR/.env"

mkdir -p "$KEYS_DIR"

echo "═══════════════════════════════════════════"
echo "  CHUM Cloud Agent Keypair Generator"
echo "═══════════════════════════════════════════"
echo ""

AGENTS=("whale-agent" "volume-agent" "momentum-agent")
ENV_NAMES=("WHALE_AGENT_KEY" "VOLUME_AGENT_KEY" "MOMENTUM_AGENT_KEY")

declare -a PUBKEYS
declare -a B58KEYS

for i in "${!AGENTS[@]}"; do
  NAME="${AGENTS[$i]}"
  KEYFILE="$KEYS_DIR/${NAME}.json"

  if [ -f "$KEYFILE" ]; then
    echo "⚠  $KEYFILE already exists — skipping generation"
  else
    echo "→  Generating $NAME keypair..."
    solana-keygen new --no-bip39-passphrase --outfile "$KEYFILE" --silent
  fi

  # Get public address
  PUBKEY=$(solana-keygen pubkey "$KEYFILE")
  PUBKEYS+=("$PUBKEY")

  # Convert JSON byte array to base58 private key using Node.js + bs58
  B58=$(node -e "
    const bs58 = require('$SCRIPT_DIR/../backend/node_modules/bs58');
    const key = require('$KEYFILE');
    console.log(bs58.encode(Buffer.from(key)));
  ")
  B58KEYS+=("$B58")

  echo "   ✓ $NAME"
  echo "     Address: $PUBKEY"
  echo ""
done

# Generate .env file
cat > "$ENV_FILE" <<ENVEOF
# CHUM Cloud Agent Configuration
# Generated by setup-agents.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

RPC_URL=https://mainnet.helius-rpc.com/?api-key=YOUR_HELIUS_KEY
${ENV_NAMES[0]}=${B58KEYS[0]}
${ENV_NAMES[1]}=${B58KEYS[1]}
${ENV_NAMES[2]}=${B58KEYS[2]}
CHUM_ROOM=chumAA7QjpFzpEtZ2XezM8onHrt8of4w35p3VMS4C6T
POLL_INTERVAL=30
WHALE_MIN_SOL=500
VOLUME_SPIKE_MULTIPLIER=3
MOMENTUM_LOOKBACK_MINUTES=15
ENVEOF

echo "═══════════════════════════════════════════"
echo "  .env written to $ENV_FILE"
echo "═══════════════════════════════════════════"
echo ""
echo "Agent Summary:"
echo "──────────────────────────────────────────"
printf "  %-18s %s\n" "whale-agent:" "${PUBKEYS[0]}"
printf "  %-18s %s\n" "volume-agent:" "${PUBKEYS[1]}"
printf "  %-18s %s\n" "momentum-agent:" "${PUBKEYS[2]}"
echo "──────────────────────────────────────────"
echo ""
echo "Fund each wallet with 0.01 SOL for transaction fees."
echo ""
echo "  solana transfer ${PUBKEYS[0]} 0.01 --allow-unfunded-recipient"
echo "  solana transfer ${PUBKEYS[1]} 0.01 --allow-unfunded-recipient"
echo "  solana transfer ${PUBKEYS[2]} 0.01 --allow-unfunded-recipient"
echo ""
echo "Or run:  node fund-agents.js"
echo ""
